// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const Icon400Million: typeof import('~icons/icon/400-million.jsx')['default']
  const IconJaded: typeof import('~icons/icon/jaded.jsx')['default']
}
export {}
